"""first migrate

Revision ID: 53e3712efc34
Revises: 
Create Date: 2024-02-04 18:44:50.562799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e3712efc34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Numeric(precision=2), nullable=False),
    sa.Column('ac', sa.Numeric(precision=2), nullable=True),
    sa.Column('strength', sa.Numeric(precision=2), nullable=False),
    sa.Column('dexterity', sa.Numeric(precision=2), nullable=False),
    sa.Column('constitution', sa.Numeric(precision=2), nullable=False),
    sa.Column('intelligence', sa.Numeric(precision=2), nullable=False),
    sa.Column('wisdom', sa.Numeric(precision=2), nullable=False),
    sa.Column('charisma', sa.Numeric(precision=2), nullable=False),
    sa.Column('spellDC', sa.Numeric(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Numeric(precision=2), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('_class', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['character_stats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('character_stats')
    # ### end Alembic commands ###
